- name: install the latest docker
  become: yes
  shell: curl -sSL https://get.docker.com/ | sh

- name: "add {{ ansible_ssh_user }} to docker group"
  become: yes
  shell: usermod -aG docker {{ ansible_ssh_user }}
