- name: install dependencies
  become: yes
  apt:
    name:
      - autotools-dev
      - automake
      - libcurl4-gnutls-dev
    state: present
    
- name: download roswell
  get_url: url={{ roswell_src }} dest={{ tmpdir }}/roswell-{{ roswell_version }}.tar.gz

- name: extract roswell
  unarchive: src={{ tmpdir }}/roswell-{{ roswell_version }}.tar.gz dest={{ tmpdir }} copy=no

- name: install roswell
  become: yes
  shell: sh ./bootstrap && ./configure && make && sudo make install
         chdir={{ tmpdir }}/roswell-{{ roswell_version }}
         creates=/usr/local/bin/ros

- file: path=~/.bashrc state=touch

- name: .bashrc
  lineinfile:
    dest=~/.bashrc
    line="PATH=~/.roswell/bin:$PATH"
    regexp="^PATH=~/.roswell/bin:\$PATH$"
    state=present
    insertafter=EOF
